apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: proyek-pancaran
  description: Komponen pertama saya dengan TechDocs
  annotations:
    # Menunjuk ke direktori tempat mkdocs.yml berada
    backstage.io/techdocs-ref: dir:. 
spec:
  type: service
  lifecycle: experimental
  owner: guests
